import { Inter } from "next/font/google";
import Link from "next/link";
import "bootstrap/dist/css/bootstrap.min.css";
// import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<nav className="mt-3 mb-3">
					<ul className="flex gap-3">
						<li>
							<Link href="/">Home</Link>
						</li>
						<li>
							<Link href="/team">Team</Link>
						</li>
						<li>
							<Link href="/player">Player</Link>
						</li>
						<li>
							<Link href="/match">Match</Link>
						</li>
					</ul>
				</nav>
				{children}
				<div>
					<footer className="text-center mt-4">
						<p>&copy; 2024 Cricket Manager. All rights reserved.</p>
					</footer>
				</div>
			</body>
		</html>
	);
}
